services:
  rfid-keyboard:
    build: .
    container_name: rfid-keyboard-service
    restart: always
    privileged: true
    volumes:
      # Host makinedeki pcscd soketini container'a bağlıyoruz
      - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
      - /dev/uinput:/dev/uinput
      - /dev/input:/dev/input
